### ISSUE TITLE
Add system include paths to compile commands

### ISSUE THREAD

**Issue by theVerySharpFlat** [wpilibsuite/gradle-cpp-vscode#32]
I found that adding using `-isystem` to specify where the system include paths are fixes code completion on MacOS for the roborio cross compiler. Another way to fix this issue is to specify the `--query-driver=$PATH_TO_ROBORIO_CROSS_GCC` so that clangd can deduce the `-isystem`s itself, so including the `-isystem` paths in the actual `compile_commands.json` would be more of a convenience fix.

As for the implementation of this, gradle itself has [GccMetadataProvider.java](https://github.com/gradle/gradle/blob/master/platforms/native/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/gcc/metadata/GccMetadataProvider.java), which should probably used through [this](https://github.com/gradle/gradle/blob/master/platforms/native/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/metadata/AbstractMetadataProvider.java#L69), although it might be easier to just copy and paste these two into this plugin and adapt them to fit our needs.

On a side note, how can I test the changes I make on this plugin on a local project?

**Comment by theVerySharpFlat** [comment]
> On a side note, how can I test the changes I make on this plugin on a local project?

Actually, this might be solved by https://github.com/wpilibsuite/native-utils/blob/main/README.md#using-custom-builds.

**Comment by ThadHouse** [comment]
https://github.com/ThadHouse/gradle-cpp-vscode/tree/better_compile_commands

I'm actually working on a branch that completely rewrites how the compile commands done. It much more closely relates to how internally gradle does it, and it does do system includes correctly.

**Comment by ThadHouse** [comment]
For doing a local test, you don't actually need to fully publish native utils. You can just run `./gradlew publishToMavenLocal` in this project, and then in a normal gradlerio project

```
id "edu.wpi.first.GradleVsCode" version "2.0.0"
```

Just add that inside the plugins block above the GradleRio plugin.

**Comment by theVerySharpFlat** [comment]
> For doing a local test, you don't actually need to fully publish native utils. You can just run `./gradlew publishToMavenLocal` in this project, and then in a normal gradlerio project
> 
> ```
> id "edu.wpi.first.GradleVsCode" version "2.0.0"
> ```
> 
> Just add that inside the plugins block above the GradleRio plugin.
> 
> As long as you don't completely break the API, this works without needing to recompile native-utils or gradlerio.

Got it. Thanks!
